name = "{{REPO_NAME}}"
main = "src/index.ts"
compatibility_date = "{{TODAYS_DATE}}"

[assets]
directory = "./dist"

[env.production]
name = "{{REPO_NAME}}-production"
[env.production.assets]
directory = "./dist"
