name = "agent-playground"
main = "src/index.ts"
compatibility_date = "2026-08-22"

[assets]
directory = "./dist"

[env.production]
name = "agent-playground-production"
[env.production.assets]
directory = "./dist"
