'use client'

import { useMemo, useState } from 'react'
import {
  Activity, Bot, ChevronDown, CircleHelp, Clock3, Command, FileJson, KeyRound,
  LockKeyhole, Menu, PanelLeft, Play, Settings2, Sparkles, Wrench, X, Zap,
} from 'lucide-react'

const navigation = [
  { label: 'Playground', description: 'Experiment with models', icon: Play },
  { label: 'Tools', description: 'Reusable capabilities', icon: Wrench },
  { label: 'Agents', description: 'Automated workflows', icon: Bot },
  { label: 'History', description: 'Your recent runs', icon: Clock3 },
]

function Logo() {
  return <div className="flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded-[10px] bg-primary text-primary-foreground shadow-sm"><Command className="size-4" strokeWidth={2.5} /></div><span className="text-[15px] font-semibold tracking-[-0.02em]">Console</span></div>
}

function Sidebar({ active, onSelect }: { active: string; onSelect: (label: string) => void }) {
  const [open, setOpen] = useState(false)
  return <>
    <button aria-label="Open navigation" className="fixed left-4 top-4 z-20 flex size-9 items-center justify-center rounded-lg border border-border bg-card text-muted-foreground shadow-sm md:hidden" onClick={() => setOpen(true)}><Menu className="size-4" /></button>
    {open && <button aria-label="Close navigation" className="fixed inset-0 z-30 bg-foreground/10 md:hidden" onClick={() => setOpen(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[252px] flex-col border-r border-border bg-sidebar px-3 py-5 transition-transform duration-200 md:static md:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex items-center justify-between px-3"><Logo /><button aria-label="Close navigation" className="flex size-8 items-center justify-center rounded-md text-muted-foreground hover:bg-accent md:hidden" onClick={() => setOpen(false)}><X className="size-4" /></button></div>
      <div className="mt-9 flex flex-col gap-6"><div><p className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Workspace</p><nav aria-label="Main navigation" className="flex flex-col gap-1">{navigation.map(({ label, description, icon: Icon }) => { const selected = active === label; return <button key={label} onClick={() => { onSelect(label); setOpen(false) }} className={`group flex items-center gap-3 rounded-lg px-3 py-2.5 text-left transition-colors ${selected ? 'bg-primary/[0.08] text-primary' : 'text-muted-foreground hover:bg-accent hover:text-foreground'}`} aria-current={selected ? 'page' : undefined}><Icon className={`size-[17px] shrink-0 ${selected ? 'text-primary' : 'text-muted-foreground group-hover:text-foreground'}`} strokeWidth={selected ? 2.3 : 1.8} /><span className="flex min-w-0 flex-col gap-0.5"><span className="text-[13px] font-medium leading-4">{label}</span><span className="truncate text-[11px] leading-4 text-muted-foreground">{description}</span></span></button> })}</nav></div><div><p className="mb-2 px-3 text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">Resources</p><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"><CircleHelp className="size-[17px]" strokeWidth={1.8} /><span className="text-[13px] font-medium">Documentation</span></button></div></div>
      <div className="mt-auto flex flex-col gap-1 border-t border-border pt-4"><button className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-muted-foreground hover:bg-accent hover:text-foreground"><Settings2 className="size-[17px]" strokeWidth={1.8} /><span className="text-[13px] font-medium">Settings</span></button><div className="mt-2 flex items-center gap-3 rounded-lg bg-accent/60 px-3 py-2.5"><div className="flex size-7 items-center justify-center rounded-full bg-primary/10 text-[11px] font-semibold text-primary">JD</div><div className="min-w-0"><p className="truncate text-[12px] font-medium">Jordan Davis</p><p className="truncate text-[11px] text-muted-foreground">Personal workspace</p></div><ChevronDown className="ml-auto size-3.5 text-muted-foreground" /></div></div>
    </aside>
  </>
}

function StatusPill({ icon: Icon, label, value, accent = false }: { icon: typeof Activity; label: string; value: string; accent?: boolean }) {
  return <div className="flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-1.5"><Icon className={`size-3.5 ${accent ? 'text-primary' : 'text-muted-foreground'}`} /><span className="hidden text-[11px] text-muted-foreground sm:inline">{label}</span><span className="text-[11px] font-medium text-foreground">{value}</span>{accent && <span className="size-1.5 rounded-full bg-primary" />}</div>
}

export default function Page() {
  const [active, setActive] = useState('Playground')
  const [prompt, setPrompt] = useState('Summarize the following text in {{style}} style:\n\n{{content}}')
  const [values, setValues] = useState<Record<string, string>>({ style: '', content: '' })
  const [model, setModel] = useState('Claude Sonnet 4')
  const [apiKey, setApiKey] = useState('sk-proj-••••••••••••••••')
  const [ran, setRan] = useState(false)
  const variables = useMemo(() => Array.from(prompt.matchAll(/\{\{\s*([\w-]+)\s*\}\}/g), match => match[1]).filter((name, index, all) => all.indexOf(name) === index), [prompt])
  const ready = variables.length > 0 && variables.every(name => values[name]?.trim())
  const run = () => { if (ready) setRan(true) }

  return <div className="flex min-h-screen bg-background text-foreground"><Sidebar active={active} onSelect={setActive} /><main className="flex min-w-0 flex-1 flex-col"><header className="flex h-[68px] items-center justify-between border-b border-border px-5 md:px-8"><div className="flex items-center gap-3 pl-10 md:pl-0"><div className="hidden size-7 items-center justify-center rounded-md bg-accent text-muted-foreground sm:flex"><PanelLeft className="size-3.5" /></div><div><h1 className="text-[14px] font-semibold tracking-[-0.01em]">Playground</h1><p className="hidden text-[11px] text-muted-foreground sm:block">A calm space to build and test</p></div></div><div className="flex items-center gap-2"><StatusPill icon={Sparkles} label="Model" value={model} accent /><StatusPill icon={KeyRound} label="API key" value="Connected" accent /></div></header>
    <section className="flex min-h-0 flex-1 flex-col gap-5 p-5 md:p-8"><div className="flex items-end justify-between"><div><p className="text-[11px] font-medium text-primary">Playground</p><h2 className="mt-1 text-[24px] font-semibold tracking-[-0.035em]">Try an idea</h2><p className="mt-1 text-[13px] text-muted-foreground">Shape a prompt, add your inputs, and see what happens.</p></div><div className="hidden items-center gap-2 text-[11px] text-muted-foreground sm:flex"><Zap className="size-3.5 text-primary" /> Ready when you are</div></div>
      <div className="grid min-h-0 flex-1 gap-5 lg:grid-cols-[minmax(0,0.95fr)_minmax(0,1.05fr)]"><div className="flex min-h-[420px] flex-col rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><label className="text-[12px] font-semibold">Prompt template</label><div className="flex items-center gap-2"><label className="sr-only" htmlFor="model">Model</label><select id="model" value={model} onChange={e => setModel(e.target.value)} className="h-8 rounded-md border border-border bg-background px-2.5 text-[11px] font-medium outline-none focus:ring-2 focus:ring-ring"><option>Claude Sonnet 4</option><option>GPT-4.1</option><option>Gemini 2.5 Pro</option></select></div></div><textarea aria-label="Prompt template" value={prompt} onChange={e => setPrompt(e.target.value)} className="mt-4 min-h-[190px] flex-1 resize-none rounded-lg border border-border bg-background p-3 font-mono text-[12px] leading-6 text-foreground outline-none placeholder:text-muted-foreground focus:ring-2 focus:ring-ring" spellCheck={false} /><div className="mt-4 flex flex-col gap-3"><p className="text-[11px] font-medium text-muted-foreground">Inputs <span className="font-normal">— detected from your template</span></p>{variables.length === 0 ? <p className="rounded-lg border border-dashed border-border p-3 text-[11px] text-muted-foreground">Type <span className="font-mono text-foreground">{'{{variable_name}}'}</span> in your prompt to add an input.</p> : <div className="flex flex-wrap gap-2">{variables.map(name => <label key={name} className="flex items-center gap-2 rounded-lg border border-border bg-background px-2.5 py-1.5"><span className="font-mono text-[11px] text-primary">{`{{${name}}}`}</span><input aria-label={`${name} value`} value={values[name] ?? ''} onChange={e => setValues({ ...values, [name]: e.target.value })} placeholder="enter value" className="w-24 bg-transparent text-[11px] outline-none placeholder:text-muted-foreground" /></label>)}</div>}</div><div className="mt-5 flex items-center gap-3 border-t border-border pt-4"><div className="relative flex min-w-0 flex-1 items-center"><LockKeyhole className="absolute left-3 size-3.5 text-muted-foreground" /><input aria-label="API key" type="password" value={apiKey} onChange={e => setApiKey(e.target.value)} title="stored locally, never sent anywhere but the model provider" className="h-9 w-full rounded-lg border border-border bg-background pl-9 pr-3 text-[11px] outline-none focus:ring-2 focus:ring-ring" /></div><span className="hidden text-[10px] text-muted-foreground xl:inline" title="stored locally, never sent anywhere but the model provider">Stored locally</span></div></div>
        <div className="flex min-h-[420px] flex-col rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[12px] font-semibold">Response</p><p className="mt-1 text-[11px] text-muted-foreground">Your model output will appear here.</p></div><button className="text-muted-foreground hover:text-foreground" aria-label="Response options"><FileJson className="size-4" /></button></div><div className="mt-4 flex min-h-0 flex-1 items-center justify-center rounded-lg border border-dashed border-border bg-background/70 p-6 text-center">{ran ? <p className="max-w-sm text-[13px] leading-6 text-foreground">Your response will appear here once the model finishes running.</p> : <div className="flex flex-col items-center gap-3 text-muted-foreground"><div className="flex size-10 items-center justify-center rounded-xl bg-accent"><Activity className="size-4 text-primary" /></div><p className="text-[12px]">Nothing yet. Run your prompt to see the result.</p></div>}</div><div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 border-t border-border pt-4 text-[11px] text-muted-foreground"><span>Tokens used <strong className="ml-1 font-medium text-foreground">—</strong></span><span>Latency <strong className="ml-1 font-medium text-foreground">—</strong></span><span>Model <strong className="ml-1 font-medium text-foreground">{model}</strong></span></div></div></div><div className="flex justify-end"><button onClick={run} disabled={!ready} className="flex items-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-[12px] font-semibold text-primary-foreground shadow-sm transition-opacity hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40"><Play className="size-3.5 fill-current" />Run</button></div></section></main></div>
}
